/**
 * MSCMSDATAFlexDocument.java
 *
 * This file was generated by MapForce 2015r4sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.mapforce.MSCMSDATAFlex;

import java.io.IOException;

import com.altova.AltovaException;
import com.altova.text.TextNode;
import com.altova.text.flex.*;
import com.altova.text.TextNodeXMLSerializer;


public class MSCMSDATAFlexDocument extends TextDocument {

	// Project Root
	static private CommandProject command_Root = new CommandProject("Root", 0);

	// SplitSingle Split_once
	static private SplitLines splitter_Split_once = new SplitLines(1);
	static private CommandSplitSingle command_Split_once = new CommandSplitSingle("Split once", splitter_Split_once, 0, 1);

	// CSV Header
	static private ColumnDelimited[] buildColumns_Header() {
		CommandStore store_Header_Field = new CommandStore("Field", 0, "");
		CommandStore store_Header_Field2 = new CommandStore("Field2", 0, "");
		CommandStore store_Header_Field3 = new CommandStore("Field3", 0, "");
		CommandStore store_Header_Field4 = new CommandStore("Field4", 0, "");
		CommandStore store_Header_Field5 = new CommandStore("Field5", 0, "");
		ColumnDelimited[] columns_Header = {
			new ColumnDelimited(store_Header_Field, "Field"),
			new ColumnDelimited(store_Header_Field2, "Field2"),
			new ColumnDelimited(store_Header_Field3, "Field3"),
			new ColumnDelimited(store_Header_Field4, "Field4"),
			new ColumnDelimited(store_Header_Field5, "Field5"),
		};
		return columns_Header;
	};
	static private ColumnDelimited[] columns_Header = buildColumns_Header();
	static private CommandCSV command_Header = new CommandCSV("Header", columns_Header, false, "\r\n", "|", '\"', '\0', true, false);

	// SplitMultiple Repeated_split
	static private SplitLines splitter_Repeated_split = new SplitLines(1);
	static private CommandSplitMultiple command_Repeated_split = new CommandSplitMultiple("Repeated split", splitter_Repeated_split, 0, 1);

	// Switch Values
	static private Condition[] conditions_Values = {
		new Condition("", Condition.ContentStartWith, "99"),
	};
	static private CommandSwitch command_Values = new CommandSwitch("Values", conditions_Values, 0);

	// CSV SKULINES
	static private ColumnDelimited[] buildColumns_SKULINES() {
		CommandStore store_SKULINES_Field24 = new CommandStore("Field24", 0, "");
		CommandStore store_SKULINES_Field22 = new CommandStore("Field2", 0, "");
		CommandStore store_SKULINES_Field32 = new CommandStore("Field3", 0, "");
		CommandStore store_SKULINES_Field42 = new CommandStore("Field4", 0, "");
		CommandStore store_SKULINES_Field52 = new CommandStore("Field5", 0, "");
		CommandStore store_SKULINES_Field6 = new CommandStore("Field6", 0, "");
		CommandStore store_SKULINES_Field7 = new CommandStore("Field7", 0, "");
		CommandStore store_SKULINES_Field8 = new CommandStore("Field8", 0, "");
		CommandStore store_SKULINES_Field9 = new CommandStore("Field9", 0, "");
		CommandStore store_SKULINES_Field10 = new CommandStore("Field10", 0, "");
		CommandStore store_SKULINES_Field11 = new CommandStore("Field11", 0, "");
		CommandStore store_SKULINES_Field12 = new CommandStore("Field12", 0, "");
		CommandStore store_SKULINES_Field13 = new CommandStore("Field13", 0, "");
		CommandStore store_SKULINES_Field14 = new CommandStore("Field14", 0, "");
		CommandStore store_SKULINES_Field15 = new CommandStore("Field15", 0, "");
		CommandStore store_SKULINES_Field16 = new CommandStore("Field16", 0, "");
		CommandStore store_SKULINES_Field17 = new CommandStore("Field17", 0, "");
		CommandStore store_SKULINES_Field18 = new CommandStore("Field18", 0, "");
		CommandStore store_SKULINES_Field19 = new CommandStore("Field19", 0, "");
		CommandStore store_SKULINES_Field20 = new CommandStore("Field20", 0, "");
		CommandStore store_SKULINES_Field21 = new CommandStore("Field21", 0, "");
		CommandStore store_SKULINES_Field222 = new CommandStore("Field22", 0, "");
		CommandStore store_SKULINES_Field23 = new CommandStore("Field23", 0, "");
		CommandStore store_SKULINES_Field242 = new CommandStore("Field242", 0, "");
		ColumnDelimited[] columns_SKULINES = {
			new ColumnDelimited(store_SKULINES_Field24, "Field24"),
			new ColumnDelimited(store_SKULINES_Field22, "Field2"),
			new ColumnDelimited(store_SKULINES_Field32, "Field3"),
			new ColumnDelimited(store_SKULINES_Field42, "Field4"),
			new ColumnDelimited(store_SKULINES_Field52, "Field5"),
			new ColumnDelimited(store_SKULINES_Field6, "Field6"),
			new ColumnDelimited(store_SKULINES_Field7, "Field7"),
			new ColumnDelimited(store_SKULINES_Field8, "Field8"),
			new ColumnDelimited(store_SKULINES_Field9, "Field9"),
			new ColumnDelimited(store_SKULINES_Field10, "Field10"),
			new ColumnDelimited(store_SKULINES_Field11, "Field11"),
			new ColumnDelimited(store_SKULINES_Field12, "Field12"),
			new ColumnDelimited(store_SKULINES_Field13, "Field13"),
			new ColumnDelimited(store_SKULINES_Field14, "Field14"),
			new ColumnDelimited(store_SKULINES_Field15, "Field15"),
			new ColumnDelimited(store_SKULINES_Field16, "Field16"),
			new ColumnDelimited(store_SKULINES_Field17, "Field17"),
			new ColumnDelimited(store_SKULINES_Field18, "Field18"),
			new ColumnDelimited(store_SKULINES_Field19, "Field19"),
			new ColumnDelimited(store_SKULINES_Field20, "Field20"),
			new ColumnDelimited(store_SKULINES_Field21, "Field21"),
			new ColumnDelimited(store_SKULINES_Field222, "Field22"),
			new ColumnDelimited(store_SKULINES_Field23, "Field23"),
			new ColumnDelimited(store_SKULINES_Field242, "Field242"),
		};
		return columns_SKULINES;
	};
	static private ColumnDelimited[] columns_SKULINES = buildColumns_SKULINES();
	static private CommandCSV command_SKULINES = new CommandCSV("SKULINES", columns_SKULINES, false, "\r\n", "|", '\"', '\0', true, false);

	public MSCMSDATAFlexDocument(int lineend)	{
		m_LineEnd = lineend;
		command_Root.setNext(command_Split_once);
		command_Split_once.setFirst(command_Header);
		command_Split_once.setNext(command_Repeated_split);
		command_Repeated_split.setNext(command_Values);
		command_Values.setNext(command_SKULINES);

		rootCommand = command_Root;
	}

	public MSCMSDATAFlexDocument()	{
		this(0);
	}
}


